name: Java CI

on: [push, pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      luceeVersion: light-6.2.0.284-SNAPSHOT
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ext-markdown
        restore-keys: |
          ${{ runner.os }}-m2
          maven-cache
    - name: Cache Lucee files
      uses: actions/cache@v4
      with:
        path: _actions/lucee/lucee-script-engine-runner/main/lucee-download-cache
        key: lucee-downloads-${{ env.luceeVersion }}
        restore-keys: |
          lucee-downloads
    - name: Build extension-markdown with Ant
      run: ant -noinput -verbose -buildfile build.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: markdown-lex
        path: dist/*.lex
    - name: Checkout Lucee
      uses: actions/checkout@v4
      with:
        repository: lucee/lucee
        path: lucee
    - name: Run Lucee Test Suite, labels="markdown"
      uses: lucee/script-runner@main
      with:
        webroot: ${{ github.workspace }}/lucee/test
        execute: /bootstrap-tests.cfm
        luceeVersion: ${{ env.luceeVersion }}
        extensionDir: ${{ github.workspace }}/dist
        extensions:
      env:
        testLabels: markdown
        testAdditional: ${{ github.workspace }}/tests